name: build

on:
  workflow_call:       # workflow is reusable
  workflow_dispatch:   # workflow can be run manually from the actions tab

jobs:    

  build:
  
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - arm64
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
          
    steps:    
      - uses: actions/checkout@v3                # project checkout      
      - uses: actions/setup-python@v4            # Python setup
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip' 
      - run: .github/scripts/checkout-all.sh
        shell: bash
      - run: .github/scripts/build-all.sh
        shell: bash
      - run: .github/scripts/analyze-all.sh
        shell: bash
      - run: .github/scripts/test-all.sh
        shell: bash
      - run: .github/scripts/doc-all.sh
        shell: bash
      - run: .github/scripts/deploy-all.sh
        shell: bash
