name: build

on:
  workflow_call:       # workflow is reusable
  workflow_dispatch:   # workflow can be run manually from the actions tab

jobs:    

  build:
  
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - arm64
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
          
    steps:
    
      - uses: actions/checkout@v3                # project checkout
      - uses: actions/setup-python@v4            # Python setup
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip' 
      
    # - uses: actions/checkout@v3
    #   with:
    #     repository: mingodad/CocoR-CPP         # Coco/R
    #     path: cocor
    #     
    # - uses: actions/checkout@v3
    #   with:
    #     repository: libsdl-org/SDL             # SDL 
    #     path: sdl          
    #     
    # - run: |
    #     pip install numpy                      # numpy
    #     pip install pandas                     # pandas
    #     pip install matplotlib                 # matplotlib
    #     pip install seaborn                    # seaborn
    #     pip freeze
    #     ls -R
          
      - name: Checkout external components
        run: ./.github/workflow/checkout-external-components.sh
        shell: bash    
          
      - name: build DSL scanner/parser
        run: |
          echo build Coco/R scanner/parser generator
          echo generate DSL scanner/parser sources for all *.atg
          
      - name: C++ artifacts
        run: |
          echo build example-dsl-cli
          echo build example-gui
          echo build example-static-library
          echo build example-dynamic-library
