name: build

on:
  workflow_call:          # workflow is reusable
  workflow_dispatch:      # workflow can be run manually from the actions tab

jobs:    

  build:
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          ls -R
      - name: Build Embedded Python Environment
        run: |
          echo install python
          echo install python modules/libraries
          echo create embedded python deployment folder 
      - name: Build DSL scanner/parser
        run: |
          echo build Coco/R parser generator
          echo generate DSL scanner/parser
      - name: Build C++ Libraries
        run: |
          echo build c++ libraries
      - name: Build C++ Apps
        run: |
          echo build c++ apps

