name: build

on:
  workflow_call:       # workflow is reusable
  workflow_dispatch:   # workflow can be run manually from the actions tab

jobs:    

  build:
  
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - arm64
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
          
    steps:
    
      - uses: actions/checkout@v3                # project checkout
      - uses: actions/setup-python@v4            # Python setup
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip' 

      - run: scripts/checkout-external-components.sh
        shell: bash    
          
      - run: |
          echo build Coco/R scanner/parser generator
          echo generate DSL scanner/parser sources for all *.atg
          
      - run: |
          echo build example-dsl-cli
          echo build example-gui
          echo build example-static-library
          echo build example-dynamic-library
