name: build

on:
  workflow_call:                                                                # workflow is reusable
  workflow_dispatch:                                                            # workflow can be run manually from the actions tab

jobs:    

  build:
  
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
          
    steps:
      - uses: actions/checkout@v3
        with:
           submodules: recursive
      
      - name: install python
        run: |
          echo install python
          echo install python modules/libraries
          echo create embedded python deployment folder 
          
      - name: update git submodules
        run: |
          echo git submodule update --init --recursive
          ls -R
          
      - name: build DSL scanner/parser
        run: |
          echo build Coco/R scanner/parser generator
          echo generate DSL scanner/parser sources for all *.atg
          
      - name: C++ artifacts
        run: |
          echo build example-dsl-cli
          echo build example-gui
          echo build example-static-library
          echo build example-dynamic-library
