name: build

on:
  workflow_call:       # workflow is reusable
  workflow_dispatch:   # workflow can be run manually from the actions tab

jobs:    

  ci:  
    runs-on: ${{ matrix.os }}    
    steps:    
      - uses: actions/checkout@v3                # checkout project
      - uses: actions/setup-python@v4            # setup Python 
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip' 
      - run: pip install -r .github/scripts/embedded-packages.txt
      - name: Execute ci script
        run: |
          ls ..
          ls
          .github/scripts/ci.sh                  # execute ci script
          ls  
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - arm64
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
