name: deploy

on:
  workflow_call:       # workflow is reusable
  workflow_dispatch:   # workflow can be run manually from the actions tab

jobs:    

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
