name: quick-dev-ci
# Minimal CI on Ubuntu to reduce turnaround times
# Run this workflow manually from the Actions tab

on:
  # push:
  #  branches: [ "main" ]
  # pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Embedded Python Environment
        run: |
          echo install python
          echo install python modules/libraries
          echo create embedded python deployment folder 
      - name: Build DSL scanner/parser
        run: |
          echo build Coco/R parser generator
          echo generate DSL scanner/parser
      - name: Build C++ Libraries
        run: |
          echo build c++ libraries
      - name: Build C++ Apps
        run: |
          echo build c++ apps


